EVAPORATION_VALUES =  [2.0, 4.0, 6.0]
CLASSIFICATION = ["low", "middle", "high", "strong"]

MIN_MOISTURE_VALUE = 50 #%
CLASSIFICATION_ANALYS_RAIN = ['low','high']
PROBABILITY_VALUE_MIN = 20 # mm
PRECIPATION_PROBABILITY_MIN = 50 # % 

SOIL_MOISTURE_LOW = 60    #% 
SOIL_MOISTURE_MIDDLE = 70 #% 
SOIL_MOISTURE_HIGH = 80 #%