"""add_user_esp_association

Revision ID: 8d43f3e3c943
Revises: edfdc76104f6
Create Date: 2026-07-28 13:03:04.501926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d43f3e3c943'
down_revision: Union[str, Sequence[str], None] = 'edfdc76104f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_esp_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('esp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['esp_id'], ['esp.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'esp_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_esp_association')
    # ### end Alembic commands ###
