"""add SoilMeasurements

Revision ID: 97ce2ed57e65
Revises: 8d43f3e3c943
Create Date: 2026-08-12 20:52:20.176046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ce2ed57e65'
down_revision: Union[str, Sequence[str], None] = '8d43f3e3c943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soil_measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('esp_id', sa.Integer(), nullable=False),
    sa.Column('irrigation', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['esp_id'], ['esp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soil_measurements')
    # ### end Alembic commands ###
