"""add key in esp

Revision ID: edfdc76104f6
Revises: 179bea4b8c5d
Create Date: 2026-07-27 15:17:23.016009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edfdc76104f6'
down_revision: Union[str, Sequence[str], None] = '179bea4b8c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('esp', sa.Column('hashed_api_key', sa.String(), nullable=False))
    op.create_index(op.f('ix_esp_hashed_api_key'), 'esp', ['hashed_api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esp_hashed_api_key'), table_name='esp')
    op.drop_column('esp', 'hashed_api_key')
    # ### end Alembic commands ###
